### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by Kyorith** [RecraftorsMC/blahaj#5]
As the title says the game simply crashes on startup. Heres the related part of the crash log:

> [03:45:57] [Render thread/ERROR]:
 Mixin apply for mod blahaj failed blahaj.mixins.json:LootTableMixin from mod blahaj -> net.minecraft.class_52: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_943 was not located in the target class net.minecraft.class_52. Using refmap blahaj_1.20-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_943 was not located in the target class net.minecraft.class_52. Using refmap blahaj_1.20-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$1(LootTableEvents.java:40) ~[fabric-loot-api-v2-2.1.4+78d798af4f-3d188c5134fd82bf.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.<clinit>(LootTableEvents.java:40) ~[fabric-loot-api-v2-2.1.4+78d798af4f-3d188c5134fd82bf.jar:?]
	at dev.architectury.event.fabric.EventHandlerImpl.registerCommon(EventHandlerImpl.java:84) ~[architectury-11.0.9-fabric.jar:?]
	at dev.architectury.event.EventHandler.registerCommon(EventHandler.java) ~[architectury-11.0.9-fabric.jar:?]
	at dev.architectury.event.EventHandler.init(EventHandler.java:39) ~[architectury-11.0.9-fabric.jar:?]
	at dev.architectury.utils.fabric.GameInstanceImpl.init(GameInstanceImpl.java:44) ~[architectury-11.0.9-fabric.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy32.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.15.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:487) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

Mods that are also in the modpack:

> 	- humblingbundle 2.3
	   |-- cardinal-components-entity 5.4.0
	   \-- cicada 0.4.6
	- sleepsooner 4.4
	- slime 1.8
	- smallernetherportals 3.6
	- sodium 0.5.5
	- sort 1.0.3
	- sound_physics_remastered 1.20.4-1.3.1
	- spawnanimations 1.9.4+mod
	- spyglass_astronomy 1.0.8-mc1.20.2
	- stackrefill 4.2
	- starlight 1.1.3+fabric.f5dcd1a
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.16+a
	- t_and_t 1.12
	- tectonic 2.1.2a
	- terrestria 6.2.0
	   |-- biolith 1.1.0-beta.1
	   |    \-- mixinextras 0.3.2
	   |-- terraform-biome-remapper-api-v1 9.0.0
	   |-- terraform-config-api-v1 9.0.0
	   |-- terraform-dirt-api-v1 9.0.0
	   |-- terraform-shapes-api-v1 9.0.0
	   |-- terraform-surfaces-api-v1 9.0.0
	   |-- terraform-tree-api-v1 9.0.0
	   |-- terraform-wood-api-v1 9.0.0
	   |-- terrestria-client 6.2.0
	   |-- terrestria-common 6.2.0
	   \-- terrestria-worldgen 6.2.0
	- through-the-lilypads-gently 1.1
	- traverse 7.2.0
	   |-- biolith 1.1.0-beta.1
	   |    \-- mixinextras 0.3.2
	   |-- terraform-biome-remapper-api-v1 9.0.0
	   |-- terraform-config-api-v1 9.0.0
	   |-- terraform-surfaces-api-v1 9.0.0
	   |-- terraform-tree-api-v1 9.0.0
	   |-- terraform-wood-api-v1 9.0.0
	   |-- traverse-client 7.2.0
	   |-- traverse-common 7.2.0
	   \-- traverse-worldgen 7.2.0
	- vanillazoom 2.3
	- waig 1.1.5
	- wakes 0.2.2
	   \-- com_github_jdiemke_delaunay-triangulator_delaunaytriangulator 1.0.0
	- yet_another_config_lib_v3 3.3.1+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- youritemsaresafe 3.6

Minecraft is on Version 1.20.4 and this happens on the currently newest version of this mod which is 0.5.1. Any help would be greatly appreciated because i simply cannot live in peace knowing there is Blahaj out there but i can't have him.

**Comment by NerjalNosk** [comment]
The mod as it is might just not be compatible with Minecraft 1.20.4. I am sorry for any inconvenience this may have caused, I am myself not much aware of the background changes that have happened between 1.20.1 and 1.20.4
Sorry for the inconvenience, I shall check in the code myself if so remove the tag as compatible with 1.20.4 on Modrinth

**Comment by Kyorith** [comment]
I see. A shame but what can you do. I hope you get around to implementing support for 1.20.4 in future updates but no pressure.

**Comment by NerjalNosk** [comment]
I actually have found the reason of the issue, and it appears only to be a thing since 1.20.2
I shall quickly make a release a patch for the concerned versions.
(I'll close the issue when said patch gets released)

**Comment by Kyorith** [comment]
Wow that was quick. Thank you very much i'll be waiting

**Comment by NerjalNosk** [comment]
Fixed in 0.5.1+1.20.2

**Comment by Kyorith** [comment]
Thank you
